POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Novo evento 2",
    "details": "teste",
    "maximumAttendees": 1
}

###
POST http://localhost:3333/events/7b89f110-8dda-4c33-8f6c-60f00fe2f36a/attendees
Content-Type: application/json


{
    "name": "Marcos v",
    "email": "marcos@gmail.com"
}